#Created by Matthew Schultz
#mschultz@hwpnj.com
import subprocess as ps
import os
from os import stat
import sys
import datetime
import csv
import xlsxwriter
import win32com.client
from win32com.client import Dispatch, constants
import pandas as pd


#must change all \ with \\ and all " "(space) with "` "(`space) for python to read the path correctly
path = 'X:\\Work` in` Progress\\517'
CSVLoc = 'T:\\Technology\\Server` Cleanup\\AUTOGENERATED_Folder_list\\Files_Larger_than_100MB_AUTOGENERATED.csv'
generate_sheet = ps.Popen('powershell.exe Get-ChildItem ' + path + ' -Recurse -ErrorAction "SilentlyContinue" -force | select Directory, Name, @{N=\'Stakeholder\';E={$_.GetAccessControl().Owner.Split(\'\\\')[1]}}, Length | Where-Object {$_.Length -gt 100MB} | Export-CSV -NoTypeInformation -Path ' + CSVLoc)
print("Generating spreadsheet")
generate_sheet.wait()
print("Spreadsheet filled")
CSVLoc = CSVLoc.replace("\\\\", "\\").replace("` ", " ")
# if we read f.csv we will write f.xlsx
wb = xlsxwriter.Workbook(CSVLoc.replace(".csv",".xlsx"))
ws = wb.add_worksheet("larger-100MB")    # your worksheet title here
with open(CSVLoc,'r') as csvfile:
    table = csv.reader(csvfile)
    i = 0
    # write each row from the csv file as text into the excel file
    # this may be adjusted to use 'excel types' explicitly (see xlsxwriter doc)
    for row in table:
        ws.write_row(i, 0, row)
        i += 1
wb.close()

#Grab data from spreadsheet
allFiles = pd.read_excel (CSVLoc[:-4] + '.xlsx', sheet_name='larger-100MB')
 #stakeHolders = pd.DataFrame(allFiles, columns= ['Stake Holder'])
 #filePaths = pd.DataFrame(allFiles, columns= ['Directory'])
 #fileNames = pd.DataFrame(allFiles, columns= ['Name'])
allFiles.insert(3, 'Date Contacted', '')
allFiles.insert(0, 'Size - MB', '')
allFiles.insert(4, 'Emailed', '')
today = datetime.datetime.now()
for i, tooLarge in allFiles.iterrows():
  stakeHolder = tooLarge['Stakeholder']
  filePath = tooLarge['Directory']
  fileName = tooLarge['Name']
  filesize = tooLarge['Length']
  if stakeHolder != "":
    emailRecip = stakeHolder[-1:]
    emailRecip += stakeHolder[:-1]
    emailRecip += "@hwpnj.com"
  if stakeHolder=="pezzutikera":
    emailRecip = "kerapezzuti@hwpnj.com"
  fileLink = filePath.replace("\\", "/")
  fileLink = fileLink.replace(" ", "%20")
  fileLink = fileLink[2:]
  if stakeHolder == "hegartyjo":
      print("John Hegarty Owned File: ")
      johnSheet = pd.read_excel (r'T:\\Technology\\Server` Cleanup\\JohnHegarty_FilesOver100MB.xlsx')
      if ((johnSheet['Directory']==tooLarge['Directory']) and johnSheet['Name']==tooLarge['Name']).any() == False:
          print("Adding to John's File")
          johnSheet.append(tooLarge)
          johnSheet.to_excel(r'T:\\Technology\\Server` Cleanup\\JohnHegarty_FilesOver100MB.xlsx')
      print("Already noted in John's File")
  if stakeHolder != "hegartyjo" and stakeHolder != "":
   # Create Email
    const=win32com.client.constants
    olMailItem = 0x0
    obj = win32com.client.Dispatch("Outlook.Application")
    newMail = obj.CreateItem(olMailItem)
    newMail.Subject = "X:\ Cleanup"
    newMail.BodyFormat = 2 #HTML Text
    newMail.HTMLBody = "<p>Hello,</p><p>&nbsp;</p><p>I have been tasked with identifying large files on the X:\ and reaching out to the stake holder to identify the need (if any) for the file.&nbsp;</p><p>Please take a moment to review this file:</p><p><a href=\"file://ntnx-fs02/promotional_wip/" + fileLink + "\">\\\\ntnx-fs02\\promotional_wip\\" + filePath + "\\" + fileName + "</a></p><p>If this file can be deleted, please do so.&nbsp; If this file should live in another location such as the V:\, please create the necessary folder, or folders, and move it there.&nbsp; If this file should be located where it is please leave it there.</p><p>&nbsp;</p><p>If you are not the stake holder, please direct me to the necessary person.</p><p>&nbsp;</p><p>Whatever you decide should be done please reply and let me know what you have done with the referenced file.</p><p>&nbsp;</p><p>Best,</p><p>Matthew Schultz</p><p>Health and Wellness Partners</p><p><a href=\"mailto:mschultz@hwpnj.com\">mschultz@hwpnj.com</a></p><p>&nbsp;</p><p><span style=\"color: black;\">The information contained in this e-mail message, together with any attachments thereto, legally protected confidential information and is intended only for the personal and confidential use of the addressee(s) named above. The message and any attachments to this message are privileged and protected communications.&nbsp; If you are not the intended recipient of this message, or authorized to receive it for the intended recipient, you have received this message in error. You are not to review, use, disseminate, distribute or copy this message, any attachments to this message, or their contents.&nbsp; If you have received this message in error, please immediately notify us by return e-mail message, and delete the original message.</span></p>"

    newMail.To = "mschultz@hwpnj.com"
    print("Emailing " + emailRecip)
    tooLarge['Emailed'] = emailRecip
    tooLarge['Date Contacted'] = str(today)
    tooLarge['Size - MB'] = "=(" + str(filesize) + "/1024)/1024"
    allFiles.loc[i] = tooLarge
    newMail.display(False)
#    newMail.Send()

allFiles.to_excel(CSVLoc[:-4] + '.xlsx')
os.remove(CSVLoc[:-4] + '.csv')
